spring:
  application:
    name: eureka-server
eureka:
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 60000 #清理服务间隔时间，毫秒
  instance:
    prefer-ip-address: true
logging:
  level:
    root: debug
---
spring:
  profiles: 8761
server:
  port: 8761
eureka:
  instance:
    hostname: 8761
  client:
    service-url:
      defaultZone: http://root:root@localhost:8762/eureka/,http://root:root@localhost:8763/eureka/
---
spring:
  profiles: 8762
server:
  port: 8762
eureka:
  instance:
    hostname: 8762
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/,http://root:root@localhost:8763/eureka/
---
spring:
  profiles: 8763
server:
  port: 8763
eureka:
  instance:
    hostname: 8763
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/,http://root:root@localhost:8762/eureka/