spring:
  application:
    name: eureka-server
eureka:
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
logging:
  level:
    root: debug
---
spring:
  profiles: 8761
server:
  port: 8761
eureka:
  instance:
    hostname: 8761
  client:
    service-url:
      defaultZone: http://root:root@localhost:8762/eureka/
---
spring:
  profiles: 8762
server:
  port: 8762
eureka:
  instance:
    hostname: 8762
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/




